name: alt_bind
channels:
  - conda-forge
dependencies:
  - altair=4.0.1=py_0

  - jaraco.itertools=5.0.0=py_0
  - jedi=0.16.0=py37_0
  - jinja2=2.11.0=py_0

  - jsonschema=3.2.0=py37_0


  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - mistune=0.8.4
  - mkl=2019.5=281
  - more-itertools=8.2.0
  - nbconvert=5.6.1
  - nbformat=5.0.4=py_0
  - notebook=6.0.3=py37_0
  - numpy=1.17.5
  - openssl=1.1.1d
  - pandas=0.25.3
  - pandoc=2.9.1.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.6.0=py_0
  - pickleshare=0.7.5=py37_1000
  - pip=20.0.2=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - pygments=2.5.2=py_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.12.3
  - pyrsistent=0.15.6
  - python=3.7.0
  - python-dateutil=2.8.1
  - pytz=2019.3=py_0
  - pywin32=225
  - pyzmq=18.1.1
  - qt=5.12.5
  - send2trash=1.5.0=py_0
  - setuptools=45.1.0=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.30.1
  - winpty=0.4.3=4
  - xlrd=1.2.0=py_0

